# Generated by Django 4.1.7 on 2023-03-17 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_follower'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('user', 'following')},
        ),
    ]
